kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    type: local
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-pvc
    namespace: default

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
        track: dev
    spec:
      containers:
      - name: "redis"
        image: "redis:alpine"
        command: ['redis-server', '--appendonly', 'yes']
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/data"
          name: redis
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis-pvc
