kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv
  labels:
    type: local
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: rabbitmq-pvc
    namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        track: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: "rabbitmq"
        image: "rabbitmq:alpine"
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 25672
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_ERLANG_COOKIE
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_VHOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: RABBITMQ_DEFAULT_VHOST
        - name: RABBITMQ_USE_LONGNAME
          value: 'false'
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq"
          name: rabbitmq
      volumes:
        - name: rabbitmq
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
